[package]
name = "utils"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../../../../shared/rust"}
config = {path = "../../../../config/rust"}
chrono = { version = "0.4.19", features = ["wasmbind"] }
thiserror = "1.0.25"
futures = "0.3.15"
itertools = "0.10.1"
async-trait = "0.1.50"
serde = { version = "1.0.126", features = ["derive"] }
serde_repr = "0.1.7"
strum = "0.21.0"
strum_macros = "0.21.1"
log = "0.4.14"
serde_json = "1.0.64"
cfg-if = "1.0.0"
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
wasm-bindgen-futures = "0.4.24"
serde-wasm-bindgen = "0.3.0"
once_cell = "1.8.0"
uuid = { version = "0.8.2", features = ["serde", "wasm-bindgen"] }
url = "2.2.2"
serde_qs = "0.8.4"
dominator = "0.5.19"
futures-signals = "0.3.22"
dominator_helpers = "0.6.3"
simple-html-template = { version = "0.2.4", features = ["wasm"] }
htmlescape = "0.3.1"
web-sys = { version = "0.3.51", features = [
    'Url',
    'Request',
    'RequestInit',
    'RequestCredentials',
    'Response',
    'RequestMode',
    'Headers',
    'Window',
    'Document',
    'Element',
    'Location',
    'Storage',
    'UrlSearchParams',
    'CssStyleDeclaration',
    'DomRect',
    'HtmlDocument',
    'HtmlImageElement',
    'History',
    'CustomEvent',
    'HtmlCanvasElement',
    'CanvasRenderingContext2d',
    'ImageData',
    'Blob'
] }
awsm_web = { version = "0.19.2", features = ["loaders", "image", "serde_iso", "canvas"] }
anyhow = "1.0.41"
rgb = "0.8.27"

[features]
quiet = []
local = ["quiet"]
release = []
sandbox = []
