[package]
name = "utils"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = {path = "../../../../shared/rust"}
config = {path = "../../../../config/rust"}
chrono = { version = "0.4.19", features = ["wasmbind"] }
futures = "0.3.8"
itertools = "0.9.0"
async-trait = "0.1.42"
serde = { version = "1.0.118", features = ["derive"] }
serde_repr = "0.1.6"
strum = "0.20.0"
strum_macros = "0.20.1"
log = "0.4.11"
serde_json = "1.0.60"
cfg-if = "1.0.0"
wasm-bindgen = "0.2.69"
js-sys = "0.3.46"
wasm-bindgen-futures = "0.4.19"
serde-wasm-bindgen = "0.1.3"
once_cell = "1.5.2"
uuid = { version = "0.8.1", features = ["serde", "wasm-bindgen"] }
url = "2.2.0"
serde_qs = "0.8.1"
dominator = "0.5.14"
futures-signals = "0.3.16"
dominator_helpers = "0.5.0"
simple-html-template = { version = "0.2.4", features = ["wasm"] }
htmlescape = "0.3.1"
web-sys = { version = "0.3.46", features = [
    'Url',
    'Request',
    'RequestInit',
    'RequestCredentials',
    'Response',
    'RequestMode',
    'Headers',
    'Window',
    'Document',
    'Element',
    'Location',
    'Storage',
    'UrlSearchParams',
    'CssStyleDeclaration',
    'DomRect',
    'HtmlDocument',
    'HtmlImageElement',
    'History',
] }
awsm_web = { version = "0.6.7", features = ["loaders", "serde_iso"] }
anyhow = "1.0.35"

[features]
quiet = []
local = ["quiet"]
release = []
sandbox = []
