[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
convert_case = "0.5.0"
anyhow = "1.0.58"
proc-macro2 = "1.0.40"
itertools = "0.10.3"
syn = { version = "1.0.103", features = ["full"] }
