[package]
name = "app-poster-common"
version = "0.1.0"
authors = ["David Komer <david.komer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../../../../utils"}
components = {path = "../../../../components"}
shared = {path = "../../../../../../../shared/rust"}
config = {path = "../../../../../../../config/rust"}
